{
 "title": "Beasley Climate",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Device", "query": "select device_id from device" }
  ]
 },
 "panels": [
  {
   "title": "Air Quality of All Locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 0 },
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  avg(pm_25) as metric,\r\n  device.device_id as name,\r\n  latitude,\r\n  longitude\r\nFROM data\r\n  JOIN device ON device.device_id = data.device_id\r\nGROUP BY data.device_id, latitude, longitude"
    }
   ]
  },
  {
   "title": "How to Use This Website",
   "type": "text",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "options": {
    "content": "# **Welcome to the Beasley Climate Website!**\n\nThis website is a collection of live data collected from devices in the Hamilton area.\nYou can see the locations of all of the devices on the left hand side, which is a map of the air quality measured by each of the sensors.\n\nBy hovering over one of the circles, you can see the device number and the air quality that it has last measured.\nYou may use that device number to see more data from that location by selecting it from the drop-down menu above the map.\n\nThe data for temperature, relative humidity, barometric pressure, UV index, and air quiality are all shown.\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  { "title": "Device Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "Device" },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature\nFROM data\nWHERE\n  $__unixEpochFilter(time) AND\n  device_id = '$Device'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pm_25,\n  pm_10\nFROM data\nWHERE\n  $__unixEpochFilter(time) AND\n  device_id = '$Device'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  pressure\nFROM data\nWHERE\n  $__unixEpochFilter(time) AND\n  device_id = '$Device'\nORDER BY time"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  uv_index\nFROM data\nWHERE\n  $__unixEpochFilter(time) AND\n  device_id = '$Device'\nORDER BY time"
    }
   ]
  },
  {
   "title": "Data",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature,\n  humidity,\n  pressure,\n  uv_index,\n  pm_10,\n  pm_25\nFROM data\nWHERE\n  $__unixEpochFilter(time) AND\n  device_id = '$Device'\nORDER BY time"
    }
   ]
  }
 ]
}